apiVersion: apps/v1
kind: Deployment
metadata:
  name: santa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: santa
  template:
    metadata:
      labels:
        app: santa
    spec:
      containers:
        - name: santa
          image: atorayew/secretsanta:latest
          ports:
            - containerPort: 8080
            
---

apiVersion: v1
kind: Service
metadata:
  name: santa-service
spec:
  selector:
    app: santa
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
