
name: CICD Pipeline  

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: repository checkout
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package --file pom.xml

    - name: artifact upload
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: target/*.jar

    - name: Trivy FS Scan
      run: |
        echo "Hello Arslanmyrat"
        trivy fs --format table -o trivy-fs-report.html .

    - name: Sonarqube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR-TOKEN: ${{ secrets.SONAR-TOKEN }}
        SONAR-HOST_URL: ${{ secrets.SONAR-HOST-URL }}
